
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'DiocamAzureRmPipeline-conn'
    subscriptionId: '7e63ef46-0ec9-4b6d-aa79-1e8fa12568b2'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'fucntionARmPipelines'
    location: 'Central US'
    templateLocation: 'Linked artifact'
    csmFile: 'CreateWebApp/diocamMainTemplate.json'
    overrideParameters: '-projectName DiocamAzureRmPipeline-repo -linkedTemplateUri https://raw.githubusercontent.com/joseocampo/DiocamAzureRmPipeline-repo/master/CreateWebApp/diocamLinkedTemplate.json'
    deploymentMode: 'Incremental'
    deploymentName: 'diocamMainTemplate'